server:
  port: 8100
spring:
  application:
    name: book-service
springdoc:
  show-actuator: true
  api-docs:
    path: book-service/v3/api-docs
resilience4j:
  ratelimiter:
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 10s